version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  admin-mongo:
    image: adicom/admin-mongo
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    depends_on:
      - mongo